name: veee
description: A Flutter package that provides a simple MVVM framework.
version: 0.9.1
homepage: https://github.com/xiprox/veee

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    